version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: kapital_bot_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 111
      POSTGRES_DB: kapital_bot
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  bot:
    build: .
    container_name: kapital_bot
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 111
      POSTGRES_DB: kapital_bot
    env_file:
      - .env
    volumes:
      - ./credentials.json:/app/credentials.json:ro
      - ./logs:/app/logs
    restart: unless-stopped

volumes:
  postgres_data: